version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: alpine:latest
    volumes:
      - ./data:/data
    command: sh -c "apk add --no-cache sqlite && tail -f /dev/null"
